version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus-app
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./volume:$PWD/src/main/resources/prometheus.yml
    healthcheck:
      test: "exit 0"

  graphana:
    image: grafana/grafana:6.5.0
    container_name: grafana
    restart: always
    hostname: localhost
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    healthcheck:
      test: "exit 0"